[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["Vector", "Store", "Vendor/Pinecone", "Area/AI", "Type/Util"]
license = ["Apache-2.0"]
name = "ai.pinecone"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.pinecone"
version = "1.1.2"

[platform.java21]
graalvmCompatible = true
