[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Pinecone", "Vector", "Store"]
license = ["Apache-2.0"]
name = "ai.pinecone"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.pinecone"
version = "1.1.1"

[platform.java21]
graalvmCompatible = true
